# Generated by Django 4.2.7 on 2023-11-25 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        ("todo_app", "0002_import_cities"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ("modified_at",)},
        ),
        migrations.RemoveField(
            model_name="todo",
            name="location",
        ),
        migrations.AddField(
            model_name="todo",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.CITIES_CITY_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.CITIES_COUNTRY_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="latitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todo",
            name="longitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
