# Generated by Django 4.2.7 on 2023-11-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0003_add_city_country_to_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="saved_temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="saved_weather",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
